name: Terraform Apply

on: 
  push:
    branches: [main]
    paths:
      - 'terraform-practice/terraform-1/**'

permissions:
  id-token: write
  contents: read

jobs:
  apply:
    runs-on: ubuntu-latest
    environment: production
    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_USE_OIDC: "true"

    steps: 
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      
      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3
        with: 
          terraform_version: "~1.9"

      - name: Terraform Init
        working-directory: terraform-practice/terraform-1
        run: terraform init

      - name: Terraform Apply
        working-directory: terraform-practice/terraform-1
        run: terraform apply -var-file="dev.tfvars" -auto-approve